algoritmo "FiboPratica"
//VARIAVEIS GLOBAIS
var
   C, T1, T2: Inteiro
Procedimento ProximoFibonacci (var A, B: inteiro)
// VARIAVEL LOCAL
var C: Inteiro
// INICIO PROCEDIMENTO
inicio
             C <- A + B
             Escreva (C)
             A <- B
             B <- c
FimProcedimento
// INICIO PROGRAMA
inicio
   T1 <- 0
   Escreva(T1)
   T2 <- 1
   Escreva(T2)
   Para C <- 3 ate 10 faca
      ProximoFibonacci(T1, T2)
   FimPara
fimalgoritmo